# Generated by Django 5.1 on 2024-08-09 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input breed name",
                        max_length=100,
                        verbose_name="Breed name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Input dog breed",
                        null=True,
                        verbose_name="Breed description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breed",
                "verbose_name_plural": "Breeds",
            },
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input dog name",
                        max_length=100,
                        verbose_name="Dog name",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Input dog photo",
                        null=True,
                        upload_to="dogs/photo",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "date_born",
                    models.DateField(
                        blank=True,
                        help_text="Input dog date born",
                        null=True,
                        verbose_name="born fate",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        help_text="Input dog poroda",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dogs",
                        to="dogs.breed",
                        verbose_name="Poroda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dog",
                "verbose_name_plural": "Dogs",
                "ordering": ["breed", "name"],
            },
        ),
    ]
